<?xml version="1.0" encoding="UTF-8"?>
<!-- <?xml-model href="gameSaved.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?> -->
<?xml-stylesheet href="gameSaved.xsl" type="text/xsl"?>
<!DOCTYPE EstrellaDAM [
        <!ELEMENT EstrellaDAM (carrera)*>
        <!ELEMENT carrera (vuelta,pilotos)*>       
        <!ELEMENT vuelta (#PCDATA)>       
        <!ELEMENT pilotos (piloto)*>
        <!ELEMENT piloto (nombre,puesto,tiempomedio,intervalo,coche)*>       
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT puesto (#PCDATA)> 
        <!ELEMENT tiempomedio (#PCDATA)>      
        <!ELEMENT intervalo (#PCDATA)>
        <!ELEMENT coche (numcoche,modelo,Infocoche)*>        
        <!ELEMENT numcoche (#PCDATA)>
        <!ELEMENT modelo (#PCDATA)>
        <!ELEMENT Infocoche (velocidad,bateria,marcha,RPM)*>
        <!ELEMENT velocidad (#PCDATA)>
        <!ELEMENT bateria (#PCDATA)>
        <!ELEMENT marcha (#PCDATA)>
        <!ELEMENT RPM (#PCDATA)>
        <!ATTLIST carrera campeonato CDATA #REQUIRED>
        <!ATTLIST vuelta num CDATA #REQUIRED>
        <!ATTLIST piloto id CDATA #REQUIRED>
        <!ATTLIST puesto posc CDATA #REQUIRED>
        <!ATTLIST coche id CDATA #REQUIRED>
        ]>
<EstrellaDAM>
    <carrera campeonato="España">
        <vuelta num="50">4/50</vuelta>
        <pilotos>
            <piloto id="1">
                <nombre>Max Verstappen</nombre>
                <puesto posc="1">1</puesto>
                <tiempomedio>1:34.193</tiempomedio>
                <intervalo>0</intervalo>
                <coche id="1">
                    <numcoche>1</numcoche>
                    <modelo>Red Bull</modelo>
                    <Infocoche>
                        <velocidad>280</velocidad>
                        <bateria>55</bateria>
                        <marcha>8</marcha>
                        <RPM>15.000</RPM>
                    </Infocoche>
                </coche>

            </piloto>
            <piloto id="11">
                <nombre>Sergio Pérez</nombre>
                <puesto posc="1">2</puesto>
                <tiempomedio>1:34.557</tiempomedio>
                <intervalo>+0.364</intervalo>               
                <coche id="1">
                    <numcoche>11</numcoche>
                    <modelo>Red Bull</modelo>
                    <Infocoche>
                        <velocidad>281</velocidad>
                        <bateria>54%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.000</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="4">
                <nombre>Lando Norris</nombre>
                <puesto posc="1">3</puesto>
                <tiempomedio>1:34.611</tiempomedio>
                <intervalo>+0.418</intervalo>                
                <coche id="1">
                    <numcoche>4</numcoche>
                    <modelo>McLaren</modelo>
                    <Infocoche>
                        <velocidad>280</velocidad>
                        <bateria>58%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.000</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="3">
                <nombre>Daniel Ricciardo</nombre>
                <puesto posc="1">4</puesto>  
                <tiempomedio>1:34.629</tiempomedio>
                <intervalo>+0.436</intervalo>
                <coche id="1">
                    <numcoche>3</numcoche>
                    <modelo>McLaren</modelo>
                    <Infocoche>
                        <velocidad>280</velocidad>
                        <bateria>33%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.500</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="6">
                <nombre>Nicholas Latifi</nombre>
                <puesto posc="1">5</puesto>
                <tiempomedio>1:34.742</tiempomedio>
                <intervalo>+0.549 </intervalo>
                <coche id="1">
                    <numcoche>6</numcoche>
                    <modelo>Williams</modelo>
                    <Infocoche>
                        <velocidad>279</velocidad>
                        <bateria>42%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.650</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="23">
                <nombre>Alexander Albon</nombre>
                <puesto posc="1">6</puesto>
                <tiempomedio>1:34.814</tiempomedio>
                <intervalo>+0.621</intervalo>
                <coche id="1">
                    <numcoche>23</numcoche>
                    <modelo>Williams</modelo>
                    <Infocoche>
                        <velocidad>279,5</velocidad>
                        <bateria>53%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.350</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="63">
                <nombre>George Russell</nombre>
                <puesto posc="1">7</puesto>
                <tiempomedio>1:34.943</tiempomedio>
                <intervalo>+0.750</intervalo>
                <coche id="1">
                    <numcoche>63</numcoche>
                    <modelo>Mercedes</modelo>
                    <Infocoche>
                        <velocidad>278.5</velocidad>
                        <bateria>45%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.850</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="44">
                <nombre> Lewis Hamilton </nombre>
                <puesto posc="1">8</puesto>
                <tiempomedio>1:35.000</tiempomedio>
                <intervalo>+0.807</intervalo>
                <coche id="1">
                    <numcoche>44</numcoche>
                    <modelo>Mercedes</modelo>
                    <Infocoche>
                        <velocidad>281.5</velocidad>
                        <bateria>63%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.550</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="55">
                <nombre> Carlos Sainz</nombre>
                <puesto posc="1">9</puesto>
                <tiempomedio>1:35.028</tiempomedio>
                <intervalo>+0.835</intervalo>
                <coche id="1">
                    <numcoche>55</numcoche>
                    <modelo>Ferrari</modelo>
                    <Infocoche>
                        <velocidad>280,5</velocidad>
                        <bateria>69%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.255</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="16">
                <nombre>Charles Leclerc</nombre>
                <puesto posc="1">10</puesto>
                <tiempomedio>1:35.050</tiempomedio>
                <intervalo>+0.857</intervalo>
                <coche id="1">
                    <numcoche>16</numcoche>
                    <modelo>Ferrari</modelo>
                    <Infocoche>
                        <velocidad>282</velocidad>
                        <bateria>58%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.255</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="14">
                <nombre> Fernando Alonso</nombre>
                <puesto posc="1">11</puesto>
                <tiempomedio>1:35.053</tiempomedio>
                <intervalo>+0.860</intervalo>
                <coche id="1">
                    <numcoche>14</numcoche>
                    <modelo>Alpine</modelo>
                    <Infocoche>
                        <velocidad>279,5</velocidad>
                        <bateria>42%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.750</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="31">
                <nombre>Esteban Ocon</nombre>
                <puesto posc="1">12</puesto>
                <tiempomedio>1:35.151</tiempomedio>
                <intervalo>+0.958</intervalo>
                <coche id="1">
                    <numcoche>31</numcoche>
                    <modelo>Alpine</modelo>
                    <Infocoche>
                        <velocidad>278</velocidad>
                        <bateria>32%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.750</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="47">
                <nombre>Mick Schumacher</nombre>
                <puesto posc="1">13</puesto>
                <tiempomedio>1:35.644</tiempomedio>
                <intervalo>+1.451</intervalo>
                <coche id="1">
                    <numcoche>47</numcoche>
                    <modelo>Haas</modelo>
                    <Infocoche>
                        <velocidad>277</velocidad>
                        <bateria>45%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.200</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="20">
                <nombre>Kevin Magnussen</nombre>
                <puesto posc="1">14</puesto>
                <tiempomedio>1:35.815</tiempomedio>
                <intervalo>+1.622</intervalo>
                <coche id="1">
                    <numcoche>20</numcoche>
                    <modelo>Haas</modelo>
                    <Infocoche>
                        <velocidad>277</velocidad>
                        <bateria>52%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.200</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="15">
                <nombre>Valtteri Bottas</nombre>
                <puesto posc="1">15</puesto>
                <tiempomedio>1:35.923</tiempomedio>
                <intervalo>+1.730</intervalo>
                <coche id="1">
                    <numcoche>15</numcoche>
                    <modelo>Alfa Romeo</modelo>
                    <Infocoche>
                        <velocidad>278</velocidad>
                        <bateria>65%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.200</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="24">
                <nombre>Guanyu Zhou</nombre>
                <puesto posc="1">16</puesto>
                <tiempomedio>1:36.304</tiempomedio>
                <intervalo>+2.111</intervalo>
                <coche id="1">
                    <numcoche>24</numcoche>
                    <modelo>Alfa Romeo</modelo>
                    <Infocoche>
                        <velocidad>277.5</velocidad>
                        <bateria>62%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.200</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="18">
                <nombre> Lance Stroll</nombre>
                <puesto posc="1">17</puesto>
                <tiempomedio>1:36.402</tiempomedio>
                <intervalo>+2.209</intervalo>
                <coche id="1">
                    <numcoche>18</numcoche>
                    <modelo>Aston Martin</modelo>
                    <Infocoche>
                        <velocidad>281</velocidad>
                        <bateria>31%</bateria>
                        <marcha>8</marcha>
                        <RPM>14.950</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="27">
                <nombre>Nico Hulkenberg</nombre>
                <puesto posc="1">18</puesto>
                <tiempomedio>1:36.536</tiempomedio>
                <intervalo>+2.343</intervalo>
                <coche id="1">
                    <numcoche>27</numcoche>
                    <modelo>Aston Martin</modelo>
                    <Infocoche>
                        <velocidad>275.5</velocidad>
                        <bateria>68%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.100</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="22">
                <nombre>Yuki Tsunoda</nombre>
                <puesto posc="1">19</puesto>
                <tiempomedio>1:36.804</tiempomedio>
                <intervalo>+2.611</intervalo>
                <coche id="1">
                    <numcoche>22</numcoche>
                    <modelo>AlphaTauri</modelo>
                    <Infocoche>
                        <velocidad>280</velocidad>
                        <bateria>55%</bateria>
                        <marcha>8</marcha>
                        <RPM>15.000</RPM>
                    </Infocoche>
                </coche>
            </piloto>
            <piloto id="10">
                <nombre> Pierre Gasly</nombre>
                <puesto posc="1"></puesto>
                <tiempomedio>DNF</tiempomedio>
                <intervalo>DNF</intervalo>
                <coche id="1">
                    <numcoche>10</numcoche>
                    <modelo>AlphaTauri</modelo>
                    <Infocoche>
                        <velocidad>0</velocidad>
                        <bateria>100%</bateria>
                        <marcha>0</marcha>
                        <RPM>0</RPM>
                    </Infocoche>
                </coche>
            </piloto>
        </pilotos>
    </carrera>
</EstrellaDAM> 